[package]
name = "aptos_fusion_plus"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
aptos_fusion_plus = "0x4a10e47494bf30cc336fb9243b30150bf351a145b937fd13647abcff9d93ea4d"

[dev-addresses]
aptos_fusion_plus = "0xde288ee6d0a2aa6e3829dc34902482c4fe971148b855b119fc1b8b398c589d23"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[dev-dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }