[package]
name = "aptos_fusion_plus"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
aptos_fusion_plus = "0x2cb2b191738c0c6311314ea06c4c8e489db62c8df1a72c11bdd3192186ed8eac"

[dev-addresses]
aptos_fusion_plus = "0x2cb2b191738c0c6311314ea06c4c8e489db62c8df1a72c11bdd3192186ed8eac"

[dependencies]
AptosFramework = { local = "/Users/swayamkarle/aptos-core/aptos-move/framework/aptos-framework"  }

[dev-dependencies]
AptosFramework = { local = "/Users/swayamkarle/aptos-core/aptos-move/framework/aptos-framework"}